### ISSUE TITLE
죽는 문제 해결 필요

### ISSUE THREAD

**Issue by perillamint** [perillamint/cirya#1]
```
00:18:48.926 [warn]  WS DISCONNECTED BECAUSE: {:remote, :closed}

00:20:14.934 [error] GenServer #PID<0.10677.0> terminating
** (UndefinedFunctionError) function nil.from/0 is undefined (module nil is not available)
    nil.from()
    (telegram_adapter) lib/telegram_adapter.ex:29: Hedwig.Adapters.Telegram.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:message, nil}

00:20:14.936 [error] GenServer #PID<0.10679.0> terminating
** (UndefinedFunctionError) function nil.from/0 is undefined (module nil is not available)
    nil.from()
    (telegram_adapter) lib/telegram_adapter.ex:29: Hedwig.Adapters.Telegram.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.10676.0>, {:undef, [{nil, :from, [], []}, {Hedwig.Adapters.Telegram, :handle_info, 2, [file: 'lib/telegram_adapter.ex', line: 29]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 616]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 686]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}

04:38:44.374 [warn]  WS DISCONNECTED BECAUSE: {:remote, :closed}

04:50:09.798 [warn]  WS DISCONNECTED BECAUSE: {:remote, :closed}

05:35:07.548 [warn]  WS DISCONNECTED BECAUSE: {:remote, :closed}

09:32:02.429 [warn]  WS DISCONNECTED BECAUSE: {:remote, :closed}

10:27:37.915 [error] GenServer Hedwig.Adapters.Telegram.TelegramServer terminating
** (Poison.SyntaxError) Unexpected token at position 0: <
    (poison) lib/poison/parser.ex:57: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    (nadia) lib/nadia/api.ex:40: Nadia.API.decode_response/1
    (nadia) lib/nadia/api.ex:30: Nadia.API.process_response/2
    (telegram_adapter) lib/telegram.ex:38: Hedwig.Adapters.Telegram.TelegramServer.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :timeout

10:27:37.917 [error] GenServer #PID<0.11343.0> terminating
** (Poison.SyntaxError) Unexpected token at position 0: <
    (poison) lib/poison/parser.ex:57: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    (nadia) lib/nadia/api.ex:40: Nadia.API.decode_response/1
    (nadia) lib/nadia/api.ex:30: Nadia.API.process_response/2
    (telegram_adapter) lib/telegram.ex:38: Hedwig.Adapters.Telegram.TelegramServer.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.11340.0>, {%Poison.SyntaxError{message: "Unexpected token at position 0: <", pos: nil, token: "<"}, [{Poison.Parser, :parse!, 2, [file: 'lib/poison/parser.ex', line: 57]}, {Poison, :decode!, 2, [file: 'lib/poison.ex', line: 83]}, {Nadia.API, :decode_response, 1, [file: 'lib/nadia/api.ex', line: 40]}, {Nadia.API, :process_response, 2, [file: 'lib/nadia/api.ex', line: 30]}, {Hedwig.Adapters.Telegram.TelegramServer, :handle_info, 2, [file: 'lib/telegram.ex', line: 38]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 616]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 686]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
```

**Comment by perillamint** [comment]
Hedwig 를 supervision tree 에 포함시켰음. 경과 관찰 필요

**Comment by perillamint** [comment]
재발함.

```
00:04:17.088 [warn]  WS DISCONNECTED BECAUSE: {:remote, :closed}

03:55:59.783 [error] GenServer Hedwig.Adapters.Telegram.TelegramServer terminating
** (MatchError) no match of right hand side value: {:error, %Nadia.Model.Error{reason: :closed}}
    (telegram_adapter) lib/telegram.ex:38: Hedwig.Adapters.Telegram.TelegramServer.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :timeout

03:55:59.784 [error] GenServer #PID<0.415.0> terminating
** (MatchError) no match of right hand side value: {:error, %Nadia.Model.Error{reason: :closed}}
    (telegram_adapter) lib/telegram.ex:38: Hedwig.Adapters.Telegram.TelegramServer.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.402.0>, {{:badmatch, {:error, %Nadia.Model.Error{reason: :closed}}}, [{Hedwig.Adapters.Telegram.TelegramServer, :handle_info, 2, [file: 'lib/telegram.ex', line: 38]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 616]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 686]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}

04:17:33.841 [warn]  WS DISCONNECTED BECAUSE: {:remote, :closed}

06:15:08.107 [warn]  WS DISCONNECTED BECAUSE: {:remote, :closed}

07:25:06.268 [warn]  Telegram message is nil. Network failure?

08:48:32.596 [warn]  WS DISCONNECTED BECAUSE: {:remote, :closed}

10:32:06.096 [error] GenServer Hedwig.Adapters.Telegram.TelegramServer terminating
** (Poison.SyntaxError) Unexpected token at position 0: <
    (poison) lib/poison/parser.ex:57: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    (nadia) lib/nadia/api.ex:40: Nadia.API.decode_response/1
    (nadia) lib/nadia/api.ex:30: Nadia.API.process_response/2
    (telegram_adapter) lib/telegram.ex:38: Hedwig.Adapters.Telegram.TelegramServer.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :timeout

10:32:06.097 [error] GenServer #PID<0.5340.0> terminating
** (Poison.SyntaxError) Unexpected token at position 0: <
    (poison) lib/poison/parser.ex:57: Poison.Parser.parse!/2
    (poison) lib/poison.ex:83: Poison.decode!/2
    (nadia) lib/nadia/api.ex:40: Nadia.API.decode_response/1
    (nadia) lib/nadia/api.ex:30: Nadia.API.process_response/2
    (telegram_adapter) lib/telegram.ex:38: Hedwig.Adapters.Telegram.TelegramServer.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.5336.0>, {%Poison.SyntaxError{message: "Unexpected token at position 0: <", pos: nil, token: "<"}, [{Poison.Parser, :parse!, 2, [file: 'lib/poison/parser.ex', line: 57]}, {Poison, :decode!, 2, [file: 'lib/poison.ex', line: 83]}, {Nadia.API, :decode_response, 1, [file: 'lib/nadia/api.ex', line: 40]}, {Nadia.API, :process_response, 2, [file: 'lib/nadia/api.ex', line: 30]}, {Hedwig.Adapters.Telegram.TelegramServer, :handle_info, 2, [file: 'lib/telegram.ex', line: 38]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 616]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 686]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}

12:41:25.499 [warn]  WS DISCONNECTED BECAUSE: {:remote, :closed}

16:03:05.181 [warn]  WS DISCONNECTED BECAUSE: {:remote, :closed}
```
